# Example of regional disaggregation of a large country
# China has contested borders, which will be removed by the module
overture_release: "latest"
crs:
  projected: "epsg:3035"
  geographic: "epsg:4326"
countries:
  "CHN":
    subtype: "region"
    source: "overture"
